[package]
name = "uperl-metacpan"
version = "0.1.0"
edition = "2024"
description = "Command line interface to the MetaCPAN API"
repository = "https://github.com/uperl/uperl-metacpan"
license = "MIT"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4", features = ["derive"] }
comfy-table = "7"
dirs = "6"
metacpan-api-modern = { git = "https://github.com/uperl/rust-metacpan-api-modern", tag = "v0.1.1" }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
] }


[package.metadata.deb]
maintainer = "Graham Ollis <devnull@wdlabs.com>"
copyright = "Graham Ollis"
extended-description = """\
Command line interface to the MetaCPAN API."""
section = "utils"
priority = "optional"
assets = [
    ["target/release/uperl-metacpan", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/uperl-metacpan/README.md", "644"],
    ["LICENSE", "usr/share/doc/uperl-metacpan/LICENSE", "644"],
]

